-- =====================================================================
-- FPSS 2027 — Caixa: pagamento DIVIDIDO em mais de uma forma
-- (ex.: parte no dinheiro + parte no cartão, ou cartão + Pix)
-- Data: 2026-10-04  —  rodar DEPOIS de 2026-10-04-carrinho-estoque-caixa.sql
-- Seguro para rodar mais de uma vez.
-- =====================================================================

-- Cada forma de pagamento usada numa venda vira uma linha aqui.
-- valor          = quanto dessa forma entra no total da venda
-- valor_recebido = (dinheiro) quanto o cliente entregou; troco = recebido - valor
create table if not exists public.pedido_pagamentos (
  id             bigint generated by default as identity primary key,
  pedido_id      bigint not null references public.pedidos(id) on delete cascade,
  forma          text not null check (forma in ('dinheiro','pix','cartao')),
  valor          numeric(10,2) not null check (valor > 0),
  valor_recebido numeric(10,2),
  troco          numeric(10,2),
  created_at     timestamptz not null default now()
);
create index if not exists pedido_pagamentos_pedido_idx on public.pedido_pagamentos (pedido_id);
alter table public.pedido_pagamentos enable row level security;

-- forma_pagamento do pedido passa a aceitar também 'misto' (sem restrição no banco)

-- Recria a função de criar pedido aceitando a lista de pagamentos
drop function if exists public.fpss_criar_pedido(jsonb, jsonb, text);

create or replace function public.fpss_criar_pedido(p_pedido jsonb, p_itens jsonb, p_prefixo text, p_pagamentos jsonb default '[]'::jsonb)
returns jsonb
language plpgsql
as $$
declare
  v_id bigint;
  v_codigo text;
  v_item jsonb;
  v_pag jsonb;
begin
  insert into public.pedidos (
    nome, sobrenome, cpf, telefone, email, produto_tipo, quantidade, valor_unitario,
    horario_retirada, valor_total, txid, pix_copia_cola, status_pagamento, status_retirada,
    status, origem, forma_pagamento, valor_recebido, troco, termo_aceito_em, termo_versao,
    vendedor_id, vendedor_nome, caixa_sessao_id, data_pagamento
  ) values (
    p_pedido->>'nome', coalesce(p_pedido->>'sobrenome',''), p_pedido->>'cpf', p_pedido->>'telefone',
    p_pedido->>'email', p_pedido->>'produto_tipo', (p_pedido->>'quantidade')::bigint,
    (p_pedido->>'valor_unitario')::numeric, p_pedido->>'horario_retirada',
    (p_pedido->>'valor_total')::numeric, p_pedido->>'txid', p_pedido->>'pix_copia_cola',
    coalesce(p_pedido->>'status_pagamento','pendente'), coalesce(p_pedido->>'status_retirada','pendente'),
    coalesce(p_pedido->>'status','pendente'), coalesce(p_pedido->>'origem','site'),
    p_pedido->>'forma_pagamento', (p_pedido->>'valor_recebido')::numeric, (p_pedido->>'troco')::numeric,
    (p_pedido->>'termo_aceito_em')::timestamptz, p_pedido->>'termo_versao',
    (p_pedido->>'vendedor_id')::uuid, p_pedido->>'vendedor_nome', (p_pedido->>'caixa_sessao_id')::bigint,
    (p_pedido->>'data_pagamento')::timestamp
  ) returning id into v_id;

  v_codigo := 'FPSS-2027-' || coalesce(nullif(p_prefixo,''),'P') || '-' || lpad(v_id::text, 6, '0');
  update public.pedidos set codigo_pedido = v_codigo where id = v_id;

  for v_item in select * from jsonb_array_elements(coalesce(p_itens, '[]'::jsonb)) loop
    insert into public.pedido_itens (pedido_id, produto_id, produto_codigo, produto_nome, preco_unitario, quantidade, exige_horario)
    values (
      v_id, (v_item->>'produto_id')::bigint, v_item->>'produto_codigo', v_item->>'produto_nome',
      (v_item->>'preco_unitario')::numeric, (v_item->>'quantidade')::int,
      coalesce((v_item->>'exige_horario')::boolean, false)
    );
  end loop;

  for v_pag in select * from jsonb_array_elements(coalesce(p_pagamentos, '[]'::jsonb)) loop
    insert into public.pedido_pagamentos (pedido_id, forma, valor, valor_recebido, troco)
    values (
      v_id, v_pag->>'forma', (v_pag->>'valor')::numeric,
      (v_pag->>'valor_recebido')::numeric, (v_pag->>'troco')::numeric
    );
  end loop;

  return jsonb_build_object('id', v_id, 'codigo_pedido', v_codigo);
end;
$$;

revoke all on function public.fpss_criar_pedido(jsonb, jsonb, text, jsonb) from public, anon, authenticated;
grant execute on function public.fpss_criar_pedido(jsonb, jsonb, text, jsonb) to service_role;

select 'Pagamento dividido instalado' as resultado;
