-- =====================================================================
-- FPSS 2027 — Distribuição de blocos de cartelas físicas
-- Data: 2026-10-05 — pode rodar mais de uma vez (seguro).
--
-- O QUE CRIA:
--   blocos_config        preço da cartela, tamanho com bônus (11), meta
--   blocos_planos        Ambulante, Comunidade, Normal, Parceria (comissão)
--   blocos               catálogo de blocos (sequencial, nº inicial/final)
--   blocos_cartelas      uma linha por cartela física e a situação dela
--   blocos_responsaveis  quem recebe os blocos (distribuidores)
--   blocos_recibos       cada entrega assinada (assinatura com o dedo)
--   blocos_entregas      bloco entregue a um responsável (com o plano)
--   blocos_acertos       prestação de contas (pode ser em partes)
--   blocos_acerto_itens  o que foi acertado de cada bloco
--   blocos_historico     quem lançou/alterou o quê (lançador)
--   user_profiles.acesso_blocos  libera a área para quem não é admin
-- Funções atômicas (dois lançadores ao mesmo tempo não se atropelam):
--   fpss_blocos_cadastrar_faixa, fpss_blocos_entregar,
--   fpss_blocos_cancelar_entrega, fpss_blocos_acertar,
--   fpss_blocos_desfazer_acerto, fpss_blocos_excluir_faixa,
--   fpss_blocos_painel
-- =====================================================================

-- ---------------------------------------------------------------------
-- 0. PERMISSÃO
-- ---------------------------------------------------------------------
alter table public.user_profiles add column if not exists acesso_blocos boolean not null default false;

-- ---------------------------------------------------------------------
-- 1. CONFIGURAÇÃO E PLANOS
-- ---------------------------------------------------------------------
create table if not exists public.blocos_config (
  id                int primary key default 1 check (id = 1),
  preco_cartela     numeric(10,2) not null default 20,
  tamanho_com_bonus int not null default 11,
  meta_devolucao    date not null default '2027-01-22',
  digitos           int not null default 5,
  atualizado_em     timestamptz not null default now()
);
insert into public.blocos_config (id) values (1) on conflict (id) do nothing;

create table if not exists public.blocos_planos (
  id           bigint generated by default as identity primary key,
  nome         text not null unique,
  comissao_pct numeric(5,2) not null default 0 check (comissao_pct between 0 and 100),
  cobra        boolean not null default true,   -- false = parceria/permuta (não paga)
  ativo        boolean not null default true,
  ordem        int not null default 0,
  descricao    text
);
insert into public.blocos_planos (nome, comissao_pct, cobra, ordem, descricao) values
  ('Ambulante / Vendedor', 50, true, 1, 'Vendedor ambulante — fica com a comissão'),
  ('Comunidade da paróquia', 50, true, 2, 'Comunidade fica com a comissão'),
  ('Normal (voluntário)', 0, true, 3, 'Pessoas da nossa comunidade — só ajudam a distribuir'),
  ('Parceria (patrocinador)', 0, false, 4, 'Permuta — não paga, só recolhe o bloco')
on conflict (nome) do nothing;

-- ---------------------------------------------------------------------
-- 1b. COMUNIDADES DA PARÓQUIA (lista "6ª FPSS - Bingo - Visitas às
--     Comunidades"). Histórico de vendas da 1ª à 5ª festa em BLOCOS DE 11
--     (0,9 = 10 cartelas). "planejado" = coluna ENVIADA 6ª (o que vamos
--     levar; a comunidade pode aceitar menos — o que vale é a entrega).
-- ---------------------------------------------------------------------
create table if not exists public.blocos_comunidades (
  id          bigint generated by default as identity primary key,
  ordem       int not null unique,
  nome        text not null,
  local       text,
  tipo        text,                -- rural, urbano, fraca, fechada
  forma       text not null default 'visita' check (forma in ('visita','caixa','fechada')),
  ativa       boolean not null default true,
  hist_1      numeric(6,1) not null default 0,
  hist_2      numeric(6,1) not null default 0,
  hist_3      numeric(6,1) not null default 0,
  hist_4      numeric(6,1) not null default 0,
  hist_5      numeric(6,1) not null default 0,
  sugestao    numeric(6,1) not null default 0,
  planejado   numeric(6,1) not null default 0,
  observacao  text,
  created_at  timestamptz not null default now()
);

insert into public.blocos_comunidades (ordem, nome, local, tipo, forma, ativa, hist_1, hist_2, hist_3, hist_4, hist_5, sugestao, planejado) values
  (1, 'São Francisco de Assis', '148/4S', 'rural', 'visita', true, 4.6, 2.5, 1.3, 1.9, 5.0, 5.0, 5.0),
  (2, 'Nossa Senhora Aparecida', '148/11S', 'rural', 'visita', true, 2.9, 1.5, 1.8, 0.1, 0.0, 2.9, 3.0),
  (3, 'Santa Catarina', '152/8S', 'fechada', 'fechada', false, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
  (4, 'Nossa Senhora do Perpétuo Socorro', '152/E25', 'urbano', 'visita', true, 2.7, 0.0, 0.9, 1.0, 4.7, 4.7, 7.0),
  (5, 'Santa Luzia', '152/8N', 'rural', 'caixa', true, 0.9, 0.4, 0.5, 1.4, 1.2, 1.4, 3.0),
  (6, 'Nossa Senhora Aparecida', '152/14N', 'rural', 'visita', true, 1.2, 1.1, 1.8, 0.0, 5.0, 5.0, 7.0),
  (7, 'São José', '152/20N', 'rural', 'caixa', true, 1.8, 2.7, 1.0, 2.0, 3.0, 3.0, 5.0),
  (8, 'Nossa Senhora das Graças', '156/4S', 'rural', 'visita', true, 1.5, 0.5, 0.9, 0.0, 1.7, 1.7, 3.0),
  (9, 'Bom Jesus', '156/9S', 'rural', 'visita', true, 1.6, 1.4, 0.2, 1.0, 0.0, 1.6, 3.0),
  (10, 'Nossa Senhora de Fátima', '156/4N', 'rural', 'caixa', true, 0.6, 0.0, 0.0, 0.0, 1.0, 1.0, 3.0),
  (11, 'Divino Espírito Santo', '156/12N', 'rural', 'caixa', true, 0.0, 0.9, 0.0, 1.0, 0.0, 1.0, 2.0),
  (12, 'São Sebastião', '156/18N', 'rural', 'visita', true, 5.6, 3.2, 1.6, 2.0, 9.0, 9.0, 11.0),
  (13, 'São José', '156/25N', 'rural', 'visita', true, 2.5, 0.9, 0.9, 2.0, 3.0, 3.0, 5.0),
  (14, 'Nossa Senhora das Graças', '160/7S', 'rural', 'caixa', true, 4.6, 1.7, 3.1, 4.1, 5.0, 5.0, 7.0),
  (15, 'São João Batista', '160/E25', 'urbano', 'visita', true, 0.0, 1.3, 0.0, 1.0, 5.5, 5.5, 7.0),
  (16, 'Jesus Nazareno', '160/8N', 'fechada', 'fechada', false, 1.5, 0.2, 1.2, 0.0, 0.0, 1.5, 0.0),
  (17, 'São João Batista', '160/14N', 'rural', 'caixa', true, 1.1, 0.0, 0.0, 0.0, 0.0, 1.1, 2.0),
  (18, 'Santa Luzia', '160/22N', 'rural', 'visita', true, 0.4, 0.0, 1.0, 0.0, 2.0, 2.0, 3.0),
  (19, 'São José', '164/10S', 'fraca', 'caixa', true, 3.6, 0.2, 1.3, 0.0, 0.0, 3.6, 5.0),
  (20, 'Santa Luzia', '164/15S', 'rural', 'visita', true, 5.5, 1.8, 4.6, 4.0, 6.0, 6.0, 8.0),
  (21, 'Nossa Senhora do Carmo', '164/5N', 'rural', 'visita', true, 3.6, 2.7, 2.9, 2.0, 7.1, 7.1, 10.0),
  (22, 'Nossa Senhora do Carmo', '164/20N', 'rural', 'visita', true, 3.6, 0.9, 0.9, 0.0, 3.6, 3.6, 5.0),
  (23, 'Nossa Senhora Aparecida', '164/24N', 'rural', 'visita', true, 2.7, 2.5, 0.9, 0.0, 2.7, 2.7, 4.0),
  (24, 'Bom Jesus', '168/E25', 'urbano', 'caixa', true, 0.0, 0.0, 0.9, 0.0, 0.0, 1.0, 2.0),
  (25, 'Maria de Nazaré', '168/12S', 'rural', 'visita', true, 1.1, 0.0, 0.0, 0.6, 5.0, 5.0, 7.0),
  (26, 'Nossa Senhora de Fátima', '168/8N', 'rural', 'visita', true, 1.9, 0.9, 1.8, 2.0, 3.0, 3.0, 5.0),
  (27, 'São Francisco de Assis', '168/16N', 'fraca', 'caixa', true, 0.7, 0.5, 0.0, 0.0, 0.0, 1.0, 2.0),
  (28, 'Cristo Rei', '172/8S', 'rural', 'visita', true, 1.6, 1.1, 0.0, 0.2, 5.1, 5.1, 7.0),
  (29, 'São José', '172/13S', 'rural', 'caixa', true, 0.9, 0.0, 0.0, 0.0, 1.5, 1.5, 2.0),
  (30, 'Santo Antônio', '172/18S', 'rural', 'visita', true, 4.6, 0.9, 3.6, 5.0, 6.0, 6.0, 8.0),
  (31, 'Santa Luzia', '172/8N', 'rural', 'caixa', true, 2.7, 0.3, 1.6, 2.3, 4.0, 4.0, 6.0),
  (32, 'São Sebastião', '172/18N', 'rural', 'visita', true, 3.6, 1.4, 2.7, 3.0, 5.0, 5.0, 7.0),
  (33, 'Nossa Senhora do Rosário', '172/32N', 'rural', 'visita', true, 3.9, 1.9, 2.7, 0.0, 1.6, 3.9, 5.0),
  (34, 'São Sebastião', '176/10S', 'rural', 'visita', true, 1.8, 0.9, 0.9, 1.4, 30.0, 30.0, 30.0),
  (35, 'São Miguel', '176/E25', 'urbano', 'visita', true, 0.0, 2.7, 4.3, 1.0, 7.4, 7.4, 10.0),
  (36, 'Santa Teresinha do Menino Jesus', 'RO 010/KM 5,5 – SD NH', 'urbano', 'visita', true, 2.9, 4.6, 2.7, 5.0, 8.9, 8.9, 15.0),
  (37, 'Nossa Senhora Aparecida', '180/4S', 'rural', 'caixa', true, 0.9, 0.9, 0.9, 1.6, 3.0, 3.0, 5.0),
  (38, 'São Geraldo', '180/7S', 'rural', 'visita', true, 0.9, 4.6, 3.2, 7.5, 4.1, 7.5, 10.0),
  (39, 'Nossa Senhora do Rosário', '180/14S', 'rural', 'visita', true, 7.3, 6.0, 3.6, 0.0, 16.0, 16.0, 20.0),
  (40, 'Nossa Senhora da Conceição', '180/15N', 'rural', 'caixa', true, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.0),
  (41, 'Nossa Senhora de Fátima', '180/21N', 'rural', 'caixa', true, 0.3, 0.1, 1.2, 1.2, 3.5, 3.5, 5.0),
  (42, 'Nossa Senhora da Glória', '180/27N', 'rural', 'visita', true, 4.6, 0.9, 2.1, 1.0, 4.0, 4.6, 6.0),
  (43, 'Santo Antônio', '184/5S', 'urbano', 'visita', true, 3.6, 3.6, 4.2, 3.0, 13.0, 13.0, 15.0),
  (44, 'Divino Espírito Santo', '184/10S', 'urbano', 'caixa', true, 3.2, 0.0, 1.8, 1.4, 2.0, 3.2, 5.0),
  (45, 'Rainha dos Apóstolos', '184/12N', 'urbano', 'visita', true, 0.4, 0.6, 0.5, 0.0, 2.7, 2.7, 4.0),
  (46, 'São João Bosco', '184/25N', 'urbano', 'caixa', true, 0.0, 0.9, 0.0, 0.0, 2.3, 2.3, 4.0),
  (48, 'São João Batista', '188/12S', 'rural', 'visita', true, 7.3, 2.6, 1.5, 1.0, 7.7, 7.7, 10.0),
  (49, 'Santo Antônio', '188/4N', 'fechada', 'fechada', false, 2.0, 0.9, 0.6, 0.0, 0.0, 2.0, 0.0),
  (50, 'Sagrado Coração de Jesus', '188/10N', 'fechada', 'fechada', false, 0.9, 0.6, 0.0, 0.0, 0.0, 1.0, 0.0),
  (51, 'Jesus Nazareno', '192/7S', 'rural', 'visita', true, 0.1, 1.8, 0.0, 0.0, 7.0, 7.0, 10.0),
  (52, 'Nossa Senhora do Carmo', 'ROLIM DE MOURA', 'urbano', 'visita', true, 3.6, 5.8, 5.9, 7.0, 10.0, 10.0, 15.0),
  (53, 'Nossa Senhora de Lurdes', '192/9N', 'rural', 'visita', true, 5.5, 0.0, 4.6, 1.9, 5.1, 5.5, 7.0),
  (54, 'Nossa Senhora Aparecida', '196/10S', 'rural', 'caixa', true, 6.5, 2.7, 5.5, 5.0, 0.0, 6.5, 5.0),
  (55, 'Santo Antônio', '196/9N', 'rural', 'caixa', true, 0.0, 1.8, 0.0, 0.0, 0.0, 1.8, 2.0),
  (56, 'Nossa Senhora da Paz', '196/17N', 'fechada', 'fechada', false, 1.6, 0.0, 0.0, 0.7, 0.0, 1.6, 0.0),
  (57, 'São Paulo', '200/10S', 'rural', 'visita', true, 1.8, 0.0, 1.8, 0.0, 9.0, 9.0, 11.0),
  (58, 'Bom Jesus', '200/8N', 'rural', 'visita', true, 0.1, 0.0, 0.0, 0.0, 3.7, 3.7, 5.0),
  (59, 'Nossa Senhora Aparecida', '204/8S', 'rural', 'visita', true, 0.0, 4.6, 0.9, 0.0, 3.0, 4.6, 5.0),
  (60, 'Santa Ana', '204/15S', 'rural', 'caixa', true, 1.8, 1.6, 0.0, 0.0, 0.0, 1.8, 3.0),
  (61, 'Nossa Senhora Aparecida', '208/11N', 'rural', 'visita', true, 2.7, 2.8, 0.0, 1.0, 1.0, 2.8, 5.0),
  (62, 'Nossa Senhora Aparecida', '208/4S', 'rural', 'caixa', true, 2.4, 0.0, 0.0, 0.0, 7.2, 7.2, 10.0),
  (63, 'Nossa Senhora da Guia', '208/10S', 'rural', 'visita', true, 4.9, 4.2, 2.7, 4.0, 9.7, 9.7, 12.0),
  (64, 'Nossa Senhora Aparecida', '208/14S', 'fechada', 'fechada', false, 3.6, 1.2, 0.0, 1.0, 0.0, 3.6, 0.0),
  (65, 'Nossa Senhora das Candeias', 'LINHA PEMAZA 01 – CAST.', 'fechada', 'fechada', false, 3.6, 1.9, 3.6, 0.0, 0.0, 3.6, 0.0),
  (66, 'Santa Isabel', 'Linha 03 – CAST.', 'rural', 'visita', true, 0.0, 0.0, 0.0, 0.0, 8.0, 8.0, 10.0),
  (67, 'São Cristóvão', 'CASTANHEIRAS', 'urbano', 'visita', true, 2.7, 2.4, 5.5, 5.0, 17.4, 17.4, 20.0),
  (68, 'Sagrado Coração de Maria', 'JARDINÓPOLIS', 'urbano', 'visita', true, 1.7, 0.7, 3.4, 4.5, 10.6, 10.6, 15.0),
  (69, 'Bom Jesus', 'NOVA ESTRELA', 'urbano', 'visita', true, 7.6, 1.1, 1.8, 2.0, 13.1, 13.1, 15.0),
  (70, 'São Francisco de Assis', 'NOVO HORIZONTE D’OESTE', 'urbano', 'visita', true, 9.1, 5.3, 6.4, 4.9, 30.0, 30.0, 35.0),
  (71, 'São Vicente de Paulo', 'ROLIM DE MOURA', 'urbano', 'visita', true, 2.3, 0.0, 3.6, 2.0, 16.0, 16.0, 20.0),
  (72, 'Santo Antônio', 'ROLIM DE MOURA', 'urbano', 'visita', true, 0.0, 1.0, 4.6, 2.0, 9.1, 9.1, 30.0),
  (73, 'Bom Jesus', 'ROLIM DE MOURA', 'urbano', 'visita', true, 0.0, 3.6, 0.9, 3.6, 9.7, 9.7, 12.0),
  (74, 'São Cristóvão', 'ROLIM DE MOURA', 'urbano', 'visita', true, 2.7, 3.9, 5.2, 7.0, 28.0, 28.0, 30.0),
  (75, 'Divino Espírito Santo', 'ROLIM DE MOURA', 'urbano', 'visita', true, 6.2, 1.6, 2.7, 4.0, 9.0, 9.0, 12.0),
  (76, 'Nossa Senhora Auxiliadora', 'ROLIM DE MOURA', 'urbano', 'visita', true, 3.6, 2.1, 6.4, 3.0, 13.5, 13.5, 20.0),
  (77, 'Imaculada Conceição', 'ROLIM DE MOURA', 'urbano', 'visita', true, 1.5, 0.0, 1.9, 3.0, 17.2, 17.2, 20.0),
  (78, 'São Tiago', 'ROLIM DE MOURA', 'urbano', 'visita', true, 1.1, 2.8, 3.1, 5.0, 25.0, 25.0, 30.0),
  (79, 'Padre Ezequiel Ramin', 'ROLIM DE MOURA', 'urbano', 'visita', true, 11.4, 0.0, 7.6, 7.0, 15.5, 15.5, 20.0),
  (80, 'Nossa Senhora de Fátima', 'ROLIM DE MOURA', 'urbano', 'visita', true, 6.7, 0.0, 6.6, 4.7, 11.2, 11.2, 15.0),
  (82, 'Sagrada Família', 'ROLIM DE MOURA', 'urbano', 'visita', true, 1.1, 0.0, 2.9, 24.1, 16.7, 24.1, 30.0),
  (83, 'Santa Rita de Cássia', 'ROLIM DE MOURA', 'urbano', 'visita', true, 0.0, 0.0, 17.4, 5.0, 8.0, 17.4, 20.0),
  (84, 'Matriz', 'ROLIM DE MOURA', 'urbano', 'visita', true, 1.8, 0.0, 0.0, 0.0, 0.0, 1.8, 3.0)
on conflict (ordem) do nothing;

-- ---------------------------------------------------------------------
-- 2. CATÁLOGO DE BLOCOS E CARTELAS
-- ---------------------------------------------------------------------
create table if not exists public.blocos (
  id              bigint generated by default as identity primary key,
  sequencial      int not null unique,
  numero_inicial  int not null,
  numero_final    int not null,
  quantidade      int generated always as (numero_final - numero_inicial + 1) stored,
  criado_por_nome text,
  created_at      timestamptz not null default now(),
  check (numero_final >= numero_inicial)
);
create index if not exists blocos_inicial_idx on public.blocos (numero_inicial);

create table if not exists public.blocos_responsaveis (
  id              bigint generated by default as identity primary key,
  nome            text not null,
  comunidade      text,
  telefone        text,
  endereco        text,
  observacao      text,
  comunidade_id   bigint references public.blocos_comunidades(id),
  criado_por_nome text,
  created_at      timestamptz not null default now()
);
alter table public.blocos_responsaveis add column if not exists comunidade_id bigint references public.blocos_comunidades(id);
create index if not exists blocos_resp_com_idx on public.blocos_responsaveis (comunidade_id);
create index if not exists blocos_resp_nome_idx on public.blocos_responsaveis (lower(nome));

-- distribuidores: pessoas da EQUIPE que entregam os blocos (Marcos,
-- André, Rafael...). Cadastro único para não ter o mesmo nome escrito
-- de jeitos diferentes; cada entrega guarda quem entregou.
create table if not exists public.blocos_distribuidores (
  id         bigint generated by default as identity primary key,
  nome       text not null,
  telefone   text,
  ativo      boolean not null default true,
  created_at timestamptz not null default now()
);
create unique index if not exists blocos_distribuidores_nome_uk on public.blocos_distribuidores (lower(trim(nome)));
insert into public.blocos_distribuidores (nome)
select n from (values ('Marcos'), ('André'), ('Rafael')) v(n)
where not exists (select 1 from public.blocos_distribuidores);

create table if not exists public.blocos_recibos (
  id             bigint generated by default as identity primary key,
  responsavel_id bigint not null references public.blocos_responsaveis(id),
  assinatura     text,               -- imagem PNG (data URL) da assinatura com o dedo
  lancador_id    uuid,
  lancador_nome  text,
  created_at     timestamptz not null default now()
);

create table if not exists public.blocos_entregas (
  id                  bigint generated by default as identity primary key,
  bloco_id            bigint not null references public.blocos(id),
  responsavel_id      bigint not null references public.blocos_responsaveis(id),
  recibo_id           bigint references public.blocos_recibos(id),
  plano_id            bigint references public.blocos_planos(id),
  plano_nome          text not null,
  comissao_pct        numeric(5,2) not null default 0,
  cobra               boolean not null default true,
  preco               numeric(10,2) not null,
  quantidade_entregue int not null,
  tem_bonus           boolean not null default false,
  bonus_usado         boolean not null default true,
  status              text not null default 'ativa' check (status in ('ativa','encerrada','cancelada')),
  lancador_id         uuid,
  lancador_nome       text,
  created_at          timestamptz not null default now()
);
alter table public.blocos_entregas add column if not exists distribuidor_id bigint references public.blocos_distribuidores(id);
alter table public.blocos_entregas add column if not exists distribuidor_nome text;
alter table public.blocos_entregas add column if not exists separada boolean not null default false;
alter table public.blocos_entregas add column if not exists entregue_em timestamptz;
update public.blocos_entregas set entregue_em = created_at where entregue_em is null and not separada;
alter table public.blocos_responsaveis add column if not exists provisorio boolean not null default false;
alter table public.blocos_recibos  add column if not exists distribuidor_id bigint references public.blocos_distribuidores(id);
alter table public.blocos_recibos  add column if not exists distribuidor_nome text;
create index if not exists blocos_entregas_resp_idx on public.blocos_entregas (responsavel_id);
create index if not exists blocos_entregas_bloco_idx on public.blocos_entregas (bloco_id);

create table if not exists public.blocos_cartelas (
  numero        int primary key,
  bloco_id      bigint not null references public.blocos(id) on delete cascade,
  status        text not null default 'estoque'
                check (status in ('estoque','com_responsavel','vendida','devolvida')),
  entrega_id    bigint references public.blocos_entregas(id),
  atualizado_em timestamptz not null default now()
);
create index if not exists blocos_cartelas_bloco_idx on public.blocos_cartelas (bloco_id);
create index if not exists blocos_cartelas_entrega_idx on public.blocos_cartelas (entrega_id);
create index if not exists blocos_cartelas_status_idx on public.blocos_cartelas (status);

create table if not exists public.blocos_acertos (
  id                bigint generated by default as identity primary key,
  responsavel_id    bigint not null references public.blocos_responsaveis(id),
  vendidas          int not null default 0,
  devolvidas        int not null default 0,
  valor_bruto       numeric(12,2) not null default 0,
  valor_comissao    numeric(12,2) not null default 0,
  valor_devido      numeric(12,2) not null default 0,
  valor_pago        numeric(12,2) not null default 0,
  observacao        text,
  lancador_id       uuid,
  lancador_nome     text,
  desfeito          boolean not null default false,
  desfeito_por_nome text,
  desfeito_em       timestamptz,
  created_at        timestamptz not null default now()
);
create index if not exists blocos_acertos_resp_idx on public.blocos_acertos (responsavel_id);

create table if not exists public.blocos_acerto_itens (
  id             bigint generated by default as identity primary key,
  acerto_id      bigint not null references public.blocos_acertos(id) on delete cascade,
  entrega_id     bigint not null references public.blocos_entregas(id),
  bloco_id       bigint not null references public.blocos(id),
  vendidas       int not null default 0,
  devolvidas     int not null default 0,
  bonus_antes    boolean,
  bonus_depois   boolean,
  valor_bruto    numeric(12,2) not null default 0,
  valor_comissao numeric(12,2) not null default 0,
  valor_devido   numeric(12,2) not null default 0,
  cartelas       jsonb not null default '[]'::jsonb   -- [{numero, de, para}]
);
create index if not exists blocos_acerto_itens_entrega_idx on public.blocos_acerto_itens (entrega_id);

create table if not exists public.blocos_historico (
  id            bigint generated by default as identity primary key,
  acao          text not null,
  descricao     text,
  dados         jsonb,
  lancador_id   uuid,
  lancador_nome text,
  created_at    timestamptz not null default now()
);
create index if not exists blocos_historico_data_idx on public.blocos_historico (created_at desc);

-- só o servidor (service_role) acessa — nada exposto ao público
alter table public.blocos_config        enable row level security;
alter table public.blocos_planos        enable row level security;
alter table public.blocos               enable row level security;
alter table public.blocos_cartelas      enable row level security;
alter table public.blocos_responsaveis  enable row level security;
alter table public.blocos_recibos       enable row level security;
alter table public.blocos_entregas      enable row level security;
alter table public.blocos_acertos       enable row level security;
alter table public.blocos_acerto_itens  enable row level security;
alter table public.blocos_historico     enable row level security;
alter table public.blocos_comunidades   enable row level security;
alter table public.blocos_distribuidores enable row level security;

-- ---------------------------------------------------------------------
-- 3. VALOR DEVIDO DE UMA ENTREGA
--    cobradas = vendidas, menos 1 de bônus quando o bloco de 11 foi
--    vendido inteiro e o vendedor ficou com a cartela bônus.
-- ---------------------------------------------------------------------
create or replace function public.fpss_blocos_valores(
  p_vendidas int, p_qtd int, p_tem_bonus boolean, p_bonus_usado boolean,
  p_preco numeric, p_comissao numeric, p_cobra boolean
) returns table (cobradas int, bruto numeric, comissao numeric, devido numeric)
language plpgsql immutable as $$
declare v_cobradas int;
begin
  v_cobradas := p_vendidas;
  if p_tem_bonus and p_bonus_usado and p_vendidas = p_qtd and p_vendidas > 0 then
    v_cobradas := p_vendidas - 1;
  end if;
  if not p_cobra then
    return query select v_cobradas, 0::numeric, 0::numeric, 0::numeric;
    return;
  end if;
  bruto := round(v_cobradas * p_preco, 2);
  comissao := round(bruto * p_comissao / 100, 2);
  return query select v_cobradas, bruto, comissao, bruto - comissao;
end;
$$;

-- ---------------------------------------------------------------------
-- 4. CADASTRAR UMA FAIXA DE BLOCOS
--    ex.: (5001, 15000, 11) → blocos de 11 da 5001 em diante; a sobra
--    do final vira um bloco menor.
-- ---------------------------------------------------------------------
create or replace function public.fpss_blocos_cadastrar_faixa(
  p_inicio int, p_fim int, p_tamanho int, p_lancador_id uuid, p_lancador_nome text
) returns jsonb
language plpgsql as $$
declare
  v_seq int; v_ini int; v_fim int; v_blocos int := 0; v_id bigint; v_conflito int;
begin
  if p_inicio is null or p_fim is null or p_tamanho is null or p_inicio < 0 or p_fim < p_inicio or p_tamanho < 1 then
    raise exception 'FAIXA_INVALIDA';
  end if;
  if p_fim - p_inicio + 1 > 60000 then
    raise exception 'FAIXA_GRANDE_DEMAIS';
  end if;

  lock table public.blocos in share row exclusive mode;

  select numero into v_conflito from public.blocos_cartelas
   where numero between p_inicio and p_fim order by numero limit 1;
  if v_conflito is not null then
    raise exception 'FAIXA_JA_CADASTRADA:%', v_conflito;
  end if;

  select coalesce(max(sequencial), 0) into v_seq from public.blocos;
  v_ini := p_inicio;
  while v_ini <= p_fim loop
    v_fim := least(v_ini + p_tamanho - 1, p_fim);
    v_seq := v_seq + 1;
    insert into public.blocos (sequencial, numero_inicial, numero_final, criado_por_nome)
    values (v_seq, v_ini, v_fim, p_lancador_nome) returning id into v_id;
    insert into public.blocos_cartelas (numero, bloco_id)
    select g, v_id from generate_series(v_ini, v_fim) g;
    v_blocos := v_blocos + 1;
    v_ini := v_fim + 1;
  end loop;

  insert into public.blocos_historico (acao, descricao, dados, lancador_id, lancador_nome)
  values ('cadastrar_faixa',
          format('Cadastrou %s blocos (cartelas %s a %s, blocos de %s)', v_blocos, p_inicio, p_fim, p_tamanho),
          jsonb_build_object('inicio', p_inicio, 'fim', p_fim, 'tamanho', p_tamanho, 'blocos', v_blocos),
          p_lancador_id, p_lancador_nome);

  return jsonb_build_object('blocos', v_blocos, 'cartelas', p_fim - p_inicio + 1, 'ultimo_sequencial', v_seq);
end;
$$;

-- excluir blocos cadastrados por engano (só se nenhuma cartela saiu do estoque)
create or replace function public.fpss_blocos_excluir_faixa(
  p_seq_inicio int, p_seq_fim int, p_lancador_id uuid, p_lancador_nome text
) returns jsonb
language plpgsql as $$
declare v_mov int; v_qtd int;
begin
  if p_seq_inicio is null or p_seq_fim is null or p_seq_fim < p_seq_inicio then
    raise exception 'FAIXA_INVALIDA';
  end if;
  select count(*) into v_mov
    from public.blocos b
    where b.sequencial between p_seq_inicio and p_seq_fim
      and (exists (select 1 from public.blocos_entregas e where e.bloco_id = b.id)
           or exists (select 1 from public.blocos_cartelas c where c.bloco_id = b.id and c.status <> 'estoque'));
  if v_mov > 0 then
    raise exception 'BLOCOS_COM_MOVIMENTO';
  end if;
  delete from public.blocos where sequencial between p_seq_inicio and p_seq_fim;
  get diagnostics v_qtd = row_count;
  insert into public.blocos_historico (acao, descricao, dados, lancador_id, lancador_nome)
  values ('excluir_faixa', format('Excluiu %s blocos (sequencial %s a %s)', v_qtd, p_seq_inicio, p_seq_fim),
          jsonb_build_object('seq_inicio', p_seq_inicio, 'seq_fim', p_seq_fim, 'blocos', v_qtd),
          p_lancador_id, p_lancador_nome);
  return jsonb_build_object('blocos', v_qtd);
end;
$$;

-- ---------------------------------------------------------------------
-- 5. ENTREGAR BLOCOS
--    p_responsavel: {id} ou {nome, comunidade, telefone, endereco}
--    p_blocos: [{bloco_id, cartelas:[numeros]}]
-- ---------------------------------------------------------------------
drop function if exists public.fpss_blocos_entregar(jsonb, jsonb, bigint, text, uuid, text);
drop function if exists public.fpss_blocos_entregar(jsonb, jsonb, bigint, text, uuid, text, bigint);
-- p_separada = true: blocos SEPARADOS para levar (ainda não entregues).
-- Nesse caso não precisa de nome/telefone/assinatura: se não vier o nome,
-- os blocos ficam com "A definir – <comunidade>" até confirmar na visita.
create or replace function public.fpss_blocos_entregar(
  p_responsavel jsonb, p_blocos jsonb, p_plano_id bigint, p_assinatura text,
  p_lancador_id uuid, p_lancador_nome text, p_distribuidor_id bigint, p_separada boolean default false
) returns jsonb
language plpgsql as $$
declare
  v_resp_id bigint; v_plano public.blocos_planos%rowtype; v_cfg public.blocos_config%rowtype;
  v_recibo bigint; v_item jsonb; v_bloco public.blocos%rowtype; v_nums int[]; v_ok int;
  v_entrega bigint; v_entregas jsonb := '[]'::jsonb; v_total int := 0; v_ruim int; v_resp_nome text;
  v_com public.blocos_comunidades%rowtype; v_com_txt text;
  v_dist public.blocos_distribuidores%rowtype;
  v_sep boolean := coalesce(p_separada, false);
begin
  if p_distribuidor_id is not null then
    select * into v_dist from public.blocos_distribuidores where id = p_distribuidor_id and ativo;
  end if;
  if v_dist.id is null and not v_sep then raise exception 'DISTRIBUIDOR_INVALIDO'; end if;

  -- comunidade escolhida na lista (opcional); o texto livre continua valendo para parceiros
  if nullif(p_responsavel->>'comunidade_id', '') is not null then
    select * into v_com from public.blocos_comunidades where id = (p_responsavel->>'comunidade_id')::bigint;
    if v_com.id is null then raise exception 'COMUNIDADE_INVALIDA'; end if;
    v_com_txt := v_com.nome || coalesce(' - ' || v_com.local, '');
  else
    v_com_txt := nullif(trim(p_responsavel->>'comunidade'), '');
  end if;

  select * into v_cfg from public.blocos_config where id = 1;
  select * into v_plano from public.blocos_planos where id = p_plano_id and ativo;
  if v_plano.id is null then raise exception 'PLANO_INVALIDO'; end if;
  if p_blocos is null or jsonb_typeof(p_blocos) <> 'array' or jsonb_array_length(p_blocos) = 0 then
    raise exception 'SEM_BLOCOS';
  end if;

  if nullif(p_responsavel->>'id', '') is not null then
    v_resp_id := (p_responsavel->>'id')::bigint;
    update public.blocos_responsaveis set
      comunidade = coalesce(v_com_txt, comunidade),
      comunidade_id = coalesce(v_com.id, comunidade_id),
      telefone   = coalesce(nullif(trim(p_responsavel->>'telefone'), ''), telefone),
      endereco   = coalesce(nullif(trim(p_responsavel->>'endereco'), ''), endereco)
    where id = v_resp_id
    returning nome into v_resp_nome;
    if v_resp_nome is null then raise exception 'RESPONSAVEL_INVALIDO'; end if;
  elsif coalesce(trim(p_responsavel->>'nome'), '') = '' then
    -- sem nome: só para blocos separados de uma comunidade/parceiro
    if not v_sep then raise exception 'RESPONSAVEL_SEM_NOME'; end if;
    if v_com_txt is null then raise exception 'SEPARAR_SEM_COMUNIDADE'; end if;
    select id, nome into v_resp_id, v_resp_nome from public.blocos_responsaveis
     where provisorio and coalesce(comunidade_id, -1) = coalesce(v_com.id, -1) and comunidade = v_com_txt
     order by id limit 1;
    if v_resp_id is null then
      insert into public.blocos_responsaveis (nome, comunidade, comunidade_id, provisorio, criado_por_nome)
      values ('A definir – ' || v_com_txt, v_com_txt, v_com.id, true, p_lancador_nome)
      returning id, nome into v_resp_id, v_resp_nome;
    end if;
  else
    insert into public.blocos_responsaveis (nome, comunidade, comunidade_id, telefone, endereco, criado_por_nome)
    values (trim(p_responsavel->>'nome'), v_com_txt, v_com.id,
            nullif(trim(p_responsavel->>'telefone'), ''), nullif(trim(p_responsavel->>'endereco'), ''), p_lancador_nome)
    returning id, nome into v_resp_id, v_resp_nome;
  end if;

  insert into public.blocos_recibos (responsavel_id, assinatura, lancador_id, lancador_nome, distribuidor_id, distribuidor_nome)
  values (v_resp_id, case when v_sep then null else p_assinatura end, p_lancador_id, p_lancador_nome, v_dist.id, v_dist.nome)
  returning id into v_recibo;

  for v_item in select * from jsonb_array_elements(p_blocos) loop
    select * into v_bloco from public.blocos where id = (v_item->>'bloco_id')::bigint;
    if v_bloco.id is null then raise exception 'BLOCO_INVALIDO'; end if;
    select array_agg(distinct x::int order by x::int) into v_nums
      from jsonb_array_elements_text(coalesce(v_item->'cartelas', '[]'::jsonb)) x;
    if v_nums is null or array_length(v_nums, 1) = 0 then raise exception 'BLOCO_SEM_CARTELAS:%', v_bloco.sequencial; end if;

    -- trava as cartelas e confere se todas estão livres e são deste bloco
    perform 1 from public.blocos_cartelas where numero = any(v_nums) for update;
    select min(n) into v_ruim from unnest(v_nums) n
      where not exists (select 1 from public.blocos_cartelas c
                        where c.numero = n and c.bloco_id = v_bloco.id and c.status in ('estoque','devolvida'));
    if v_ruim is not null then raise exception 'CARTELA_INDISPONIVEL:%', v_ruim; end if;

    insert into public.blocos_entregas (bloco_id, responsavel_id, recibo_id, plano_id, plano_nome, comissao_pct, cobra,
                                        preco, quantidade_entregue, tem_bonus, bonus_usado, lancador_id, lancador_nome,
                                        distribuidor_id, distribuidor_nome, separada, entregue_em)
    values (v_bloco.id, v_resp_id, v_recibo, v_plano.id, v_plano.nome, v_plano.comissao_pct, v_plano.cobra,
            v_cfg.preco_cartela, array_length(v_nums, 1),
            (v_bloco.quantidade = v_cfg.tamanho_com_bonus and array_length(v_nums, 1) = v_cfg.tamanho_com_bonus),
            true, p_lancador_id, p_lancador_nome, v_dist.id, v_dist.nome, v_sep, case when v_sep then null else now() end)
    returning id into v_entrega;

    update public.blocos_cartelas set status = 'com_responsavel', entrega_id = v_entrega, atualizado_em = now()
     where numero = any(v_nums);
    get diagnostics v_ok = row_count;
    v_total := v_total + v_ok;
    v_entregas := v_entregas || jsonb_build_object('entrega_id', v_entrega, 'sequencial', v_bloco.sequencial,
                    'numero_inicial', v_bloco.numero_inicial, 'numero_final', v_bloco.numero_final, 'quantidade', v_ok);
  end loop;

  insert into public.blocos_historico (acao, descricao, dados, lancador_id, lancador_nome)
  values (case when v_sep then 'separacao' else 'entrega' end,
          case when v_sep
            then format('Separou %s cartelas (%s bloco(s)) para %s — %s (ainda não entregues)', v_total, jsonb_array_length(v_entregas), v_resp_nome, v_plano.nome)
            else format('%s entregou %s cartelas (%s bloco(s)) para %s — %s', v_dist.nome, v_total, jsonb_array_length(v_entregas), v_resp_nome, v_plano.nome) end,
          jsonb_build_object('recibo_id', v_recibo, 'responsavel_id', v_resp_id, 'entregas', v_entregas, 'separada', v_sep),
          p_lancador_id, p_lancador_nome);

  return jsonb_build_object('recibo_id', v_recibo, 'responsavel_id', v_resp_id, 'cartelas', v_total, 'entregas', v_entregas, 'separada', v_sep);
end;
$$;

-- CONFIRMAR A ENTREGA de blocos separados (visita feita): informa quem
-- recebeu (cadastro existente ou novo), quem entregou e a assinatura.
create or replace function public.fpss_blocos_confirmar_separacao(
  p_entregas bigint[], p_responsavel jsonb, p_distribuidor_id bigint, p_assinatura text,
  p_lancador_id uuid, p_lancador_nome text
) returns jsonb
language plpgsql as $$
declare
  v_dist public.blocos_distribuidores%rowtype; v_origem public.blocos_responsaveis%rowtype;
  v_resp_id bigint; v_resp_nome text; v_recibo bigint; v_qtd int; v_cartelas int;
begin
  select * into v_dist from public.blocos_distribuidores where id = p_distribuidor_id and ativo;
  if v_dist.id is null then raise exception 'DISTRIBUIDOR_INVALIDO'; end if;
  if p_entregas is null or array_length(p_entregas, 1) is null then raise exception 'SEM_BLOCOS'; end if;

  perform 1 from public.blocos_entregas where id = any(p_entregas) for update;
  if exists (select 1 from public.blocos_entregas where id = any(p_entregas) and (not separada or status <> 'ativa')) then
    raise exception 'ENTREGA_NAO_SEPARADA';
  end if;
  if (select count(distinct responsavel_id) from public.blocos_entregas where id = any(p_entregas)) <> 1 then
    raise exception 'ENTREGA_INVALIDA';
  end if;
  select r.* into v_origem from public.blocos_responsaveis r
    join public.blocos_entregas e on e.responsavel_id = r.id where e.id = p_entregas[1];

  if nullif(p_responsavel->>'id', '') is not null then
    v_resp_id := (p_responsavel->>'id')::bigint;
    update public.blocos_responsaveis set
      telefone = coalesce(nullif(trim(p_responsavel->>'telefone'), ''), telefone),
      endereco = coalesce(nullif(trim(p_responsavel->>'endereco'), ''), endereco),
      comunidade = coalesce(comunidade, v_origem.comunidade),
      comunidade_id = coalesce(comunidade_id, v_origem.comunidade_id)
    where id = v_resp_id and not provisorio
    returning nome into v_resp_nome;
    if v_resp_nome is null then raise exception 'RESPONSAVEL_INVALIDO'; end if;
  else
    if coalesce(trim(p_responsavel->>'nome'), '') = '' then raise exception 'RESPONSAVEL_SEM_NOME'; end if;
    insert into public.blocos_responsaveis (nome, comunidade, comunidade_id, telefone, endereco, criado_por_nome)
    values (trim(p_responsavel->>'nome'), v_origem.comunidade, v_origem.comunidade_id,
            nullif(trim(p_responsavel->>'telefone'), ''), nullif(trim(p_responsavel->>'endereco'), ''), p_lancador_nome)
    returning id, nome into v_resp_id, v_resp_nome;
  end if;

  insert into public.blocos_recibos (responsavel_id, assinatura, lancador_id, lancador_nome, distribuidor_id, distribuidor_nome)
  values (v_resp_id, p_assinatura, p_lancador_id, p_lancador_nome, v_dist.id, v_dist.nome) returning id into v_recibo;

  update public.blocos_entregas set responsavel_id = v_resp_id, recibo_id = v_recibo, separada = false, entregue_em = now(),
         distribuidor_id = v_dist.id, distribuidor_nome = v_dist.nome
   where id = any(p_entregas);
  get diagnostics v_qtd = row_count;
  select coalesce(sum(quantidade_entregue), 0) into v_cartelas from public.blocos_entregas where id = any(p_entregas);

  -- o "A definir" some quando não tiver mais nada
  if v_origem.provisorio and v_origem.id <> v_resp_id
     and not exists (select 1 from public.blocos_entregas where responsavel_id = v_origem.id)
     and not exists (select 1 from public.blocos_acertos where responsavel_id = v_origem.id) then
    delete from public.blocos_recibos where responsavel_id = v_origem.id;
    delete from public.blocos_responsaveis where id = v_origem.id;
  end if;

  insert into public.blocos_historico (acao, descricao, dados, lancador_id, lancador_nome)
  values ('confirmar_separacao', format('%s entregou %s bloco(s) separados (%s cartelas) para %s', v_dist.nome, v_qtd, v_cartelas, v_resp_nome),
          jsonb_build_object('recibo_id', v_recibo, 'responsavel_id', v_resp_id, 'entregas', p_entregas), p_lancador_id, p_lancador_nome);

  return jsonb_build_object('recibo_id', v_recibo, 'responsavel_id', v_resp_id, 'blocos', v_qtd, 'cartelas', v_cartelas);
end;
$$;

-- cancelar uma entrega lançada errado (só se ainda não teve acerto)
create or replace function public.fpss_blocos_cancelar_entrega(
  p_entrega_id bigint, p_lancador_id uuid, p_lancador_nome text
) returns jsonb
language plpgsql as $$
declare v_e public.blocos_entregas%rowtype; v_qtd int; v_seq int; v_nome text;
begin
  select * into v_e from public.blocos_entregas where id = p_entrega_id for update;
  if v_e.id is null or v_e.status = 'cancelada' then raise exception 'ENTREGA_INVALIDA'; end if;
  if exists (select 1 from public.blocos_acerto_itens i join public.blocos_acertos a on a.id = i.acerto_id
             where i.entrega_id = p_entrega_id and not a.desfeito) then
    raise exception 'ENTREGA_COM_ACERTO';
  end if;
  update public.blocos_cartelas set status = 'estoque', entrega_id = null, atualizado_em = now()
   where entrega_id = p_entrega_id and status = 'com_responsavel';
  get diagnostics v_qtd = row_count;
  update public.blocos_entregas set status = 'cancelada' where id = p_entrega_id;
  select sequencial into v_seq from public.blocos where id = v_e.bloco_id;
  select nome into v_nome from public.blocos_responsaveis where id = v_e.responsavel_id;
  insert into public.blocos_historico (acao, descricao, dados, lancador_id, lancador_nome)
  values ('cancelar_entrega', format('Cancelou a entrega do bloco %s para %s (%s cartelas voltaram ao estoque)', v_seq, v_nome, v_qtd),
          jsonb_build_object('entrega_id', p_entrega_id, 'cartelas', v_qtd), p_lancador_id, p_lancador_nome);
  return jsonb_build_object('cartelas', v_qtd);
end;
$$;

-- ---------------------------------------------------------------------
-- 6. ACERTO (prestação de contas) — pode ser em partes
--    p_itens: [{entrega_id, cartelas:{"5001":"vendida","5002":"devolvida"}, bonus_usado}]
--    Só mexe em cartelas que estão "com_responsavel" (as já acertadas
--    só mudam desfazendo o acerto). Cartela não listada continua com ele.
-- ---------------------------------------------------------------------
create or replace function public.fpss_blocos_acertar(
  p_responsavel_id bigint, p_itens jsonb, p_valor_pago numeric, p_observacao text,
  p_lancador_id uuid, p_lancador_nome text
) returns jsonb
language plpgsql as $$
declare
  v_item jsonb; v_e public.blocos_entregas%rowtype; v_kv record; v_num int; v_para text;
  v_v0 int; v_v1 int; v_b0 boolean; v_b1 boolean; r0 record; r1 record;
  v_mud jsonb; v_vend int; v_dev int; v_acerto bigint; v_resp_nome text;
  t_vend int := 0; t_dev int := 0; t_bruto numeric := 0; t_com numeric := 0; t_dev_valor numeric := 0;
  v_itens_out jsonb := '[]'::jsonb;
begin
  select nome into v_resp_nome from public.blocos_responsaveis where id = p_responsavel_id;
  if v_resp_nome is null then raise exception 'RESPONSAVEL_INVALIDO'; end if;
  if coalesce(p_valor_pago, 0) < 0 then raise exception 'VALOR_INVALIDO'; end if;

  insert into public.blocos_acertos (responsavel_id, valor_pago, observacao, lancador_id, lancador_nome)
  values (p_responsavel_id, coalesce(p_valor_pago, 0), nullif(trim(p_observacao), ''), p_lancador_id, p_lancador_nome)
  returning id into v_acerto;

  for v_item in select * from jsonb_array_elements(coalesce(p_itens, '[]'::jsonb)) loop
    select * into v_e from public.blocos_entregas where id = (v_item->>'entrega_id')::bigint for update;
    if v_e.id is null or v_e.responsavel_id <> p_responsavel_id or v_e.status = 'cancelada' then
      raise exception 'ENTREGA_INVALIDA';
    end if;
    if v_e.separada then raise exception 'ENTREGA_SEPARADA'; end if;

    select count(*) into v_v0 from public.blocos_cartelas where entrega_id = v_e.id and status = 'vendida';
    v_b0 := v_e.bonus_usado;
    v_b1 := case when v_item ? 'bonus_usado' then coalesce((v_item->>'bonus_usado')::boolean, v_b0) else v_b0 end;

    v_mud := '[]'::jsonb; v_vend := 0; v_dev := 0;
    for v_kv in select key, value from jsonb_each_text(coalesce(v_item->'cartelas', '{}'::jsonb)) loop
      v_num := v_kv.key::int;
      v_para := v_kv.value;
      if v_para = 'com_responsavel' then continue; end if;
      if v_para not in ('vendida','devolvida') then raise exception 'SITUACAO_INVALIDA'; end if;
      update public.blocos_cartelas set status = v_para, atualizado_em = now()
       where numero = v_num and entrega_id = v_e.id and status = 'com_responsavel';
      if not found then raise exception 'CARTELA_JA_ACERTADA:%', v_num; end if;
      v_mud := v_mud || jsonb_build_object('numero', v_num, 'de', 'com_responsavel', 'para', v_para);
      if v_para = 'vendida' then v_vend := v_vend + 1; else v_dev := v_dev + 1; end if;
    end loop;

    if v_vend = 0 and v_dev = 0 and v_b0 = v_b1 then continue; end if;

    v_v1 := v_v0 + v_vend;
    select * into r0 from public.fpss_blocos_valores(v_v0, v_e.quantidade_entregue, v_e.tem_bonus, v_b0, v_e.preco, v_e.comissao_pct, v_e.cobra);
    select * into r1 from public.fpss_blocos_valores(v_v1, v_e.quantidade_entregue, v_e.tem_bonus, v_b1, v_e.preco, v_e.comissao_pct, v_e.cobra);

    update public.blocos_entregas set bonus_usado = v_b1,
      status = case when exists (select 1 from public.blocos_cartelas where entrega_id = v_e.id and status = 'com_responsavel')
                    then 'ativa' else 'encerrada' end
     where id = v_e.id;

    insert into public.blocos_acerto_itens (acerto_id, entrega_id, bloco_id, vendidas, devolvidas, bonus_antes, bonus_depois,
                                            valor_bruto, valor_comissao, valor_devido, cartelas)
    values (v_acerto, v_e.id, v_e.bloco_id, v_vend, v_dev, v_b0, v_b1,
            r1.bruto - r0.bruto, r1.comissao - r0.comissao, r1.devido - r0.devido, v_mud);

    t_vend := t_vend + v_vend; t_dev := t_dev + v_dev;
    t_bruto := t_bruto + (r1.bruto - r0.bruto);
    t_com := t_com + (r1.comissao - r0.comissao);
    t_dev_valor := t_dev_valor + (r1.devido - r0.devido);
    v_itens_out := v_itens_out || jsonb_build_object('entrega_id', v_e.id, 'vendidas', v_vend, 'devolvidas', v_dev,
                     'valor_devido', r1.devido - r0.devido);
  end loop;

  if t_vend = 0 and t_dev = 0 and jsonb_array_length(v_itens_out) = 0 and coalesce(p_valor_pago, 0) = 0 then
    raise exception 'ACERTO_VAZIO';
  end if;

  update public.blocos_acertos set vendidas = t_vend, devolvidas = t_dev, valor_bruto = t_bruto,
         valor_comissao = t_com, valor_devido = t_dev_valor
   where id = v_acerto;

  insert into public.blocos_historico (acao, descricao, dados, lancador_id, lancador_nome)
  values ('acerto', format('Acerto de %s: %s vendidas, %s devolvidas, devido R$ %s, pago R$ %s',
                           v_resp_nome, t_vend, t_dev, replace(to_char(t_dev_valor, 'FM9999990.00'), '.', ','), replace(to_char(coalesce(p_valor_pago,0), 'FM9999990.00'), '.', ',')),
          jsonb_build_object('acerto_id', v_acerto, 'responsavel_id', p_responsavel_id, 'itens', v_itens_out),
          p_lancador_id, p_lancador_nome);

  return jsonb_build_object('acerto_id', v_acerto, 'vendidas', t_vend, 'devolvidas', t_dev,
                            'valor_bruto', t_bruto, 'valor_comissao', t_com, 'valor_devido', t_dev_valor,
                            'valor_pago', coalesce(p_valor_pago, 0), 'itens', v_itens_out);
end;
$$;

-- desfazer um acerto lançado errado (as cartelas voltam a ficar "com ele")
create or replace function public.fpss_blocos_desfazer_acerto(
  p_acerto_id bigint, p_lancador_id uuid, p_lancador_nome text
) returns jsonb
language plpgsql as $$
declare v_a public.blocos_acertos%rowtype; v_i record; v_c jsonb; v_resp text; v_qtd int := 0;
begin
  select * into v_a from public.blocos_acertos where id = p_acerto_id for update;
  if v_a.id is null or v_a.desfeito then raise exception 'ACERTO_INVALIDO'; end if;

  -- não deixa desfazer se depois dele veio outro acerto nos mesmos blocos
  if exists (select 1 from public.blocos_acerto_itens i2 join public.blocos_acertos a2 on a2.id = i2.acerto_id
             where not a2.desfeito and a2.id > v_a.id
               and i2.entrega_id in (select entrega_id from public.blocos_acerto_itens where acerto_id = v_a.id)) then
    raise exception 'ACERTO_POSTERIOR';
  end if;

  for v_i in select * from public.blocos_acerto_itens where acerto_id = v_a.id loop
    perform 1 from public.blocos_entregas where id = v_i.entrega_id for update;
    for v_c in select * from jsonb_array_elements(v_i.cartelas) loop
      update public.blocos_cartelas set status = 'com_responsavel', atualizado_em = now()
       where numero = (v_c->>'numero')::int and entrega_id = v_i.entrega_id and status = (v_c->>'para');
      if not found then raise exception 'CARTELA_ALTERADA:%', v_c->>'numero'; end if;
      v_qtd := v_qtd + 1;
    end loop;
    update public.blocos_entregas set bonus_usado = coalesce(v_i.bonus_antes, bonus_usado), status = 'ativa'
     where id = v_i.entrega_id;
  end loop;

  update public.blocos_acertos set desfeito = true, desfeito_por_nome = p_lancador_nome, desfeito_em = now()
   where id = v_a.id;
  select nome into v_resp from public.blocos_responsaveis where id = v_a.responsavel_id;
  insert into public.blocos_historico (acao, descricao, dados, lancador_id, lancador_nome)
  values ('desfazer_acerto', format('Desfez o acerto #%s de %s (%s cartelas voltaram a ficar com ele; pagamento de R$ %s estornado)',
                                    v_a.id, v_resp, v_qtd, replace(to_char(v_a.valor_pago, 'FM9999990.00'), '.', ',')),
          jsonb_build_object('acerto_id', v_a.id), p_lancador_id, p_lancador_nome);
  return jsonb_build_object('cartelas', v_qtd);
end;
$$;

-- ---------------------------------------------------------------------
-- 7. RESUMO POR RESPONSÁVEL (lista e ficha)
-- ---------------------------------------------------------------------
create or replace view public.blocos_resumo_responsavel as
select r.id, r.nome, r.comunidade, r.telefone, r.endereco, r.created_at,
  coalesce(c.com_responsavel, 0) as com_responsavel,
  coalesce(c.vendidas, 0)        as vendidas,
  coalesce(c.devolvidas, 0)      as devolvidas,
  coalesce(e.entregues, 0)       as entregues,
  coalesce(e.blocos, 0)          as blocos,
  e.ultima_entrega,
  coalesce(a.devido, 0)          as valor_devido,
  coalesce(a.pago, 0)            as valor_pago,
  coalesce(a.devido, 0) - coalesce(a.pago, 0) as saldo,
  a.ultimo_acerto,
  r.comunidade_id,
  r.provisorio,
  coalesce(e.separados, 0)       as blocos_separados
from public.blocos_responsaveis r
left join (
  select e.responsavel_id,
    count(*) filter (where c.status = 'com_responsavel') as com_responsavel,
    count(*) filter (where c.status = 'vendida')         as vendidas,
    count(*) filter (where c.status = 'devolvida')       as devolvidas
  from public.blocos_cartelas c join public.blocos_entregas e on e.id = c.entrega_id
  where e.status <> 'cancelada'
  group by e.responsavel_id
) c on c.responsavel_id = r.id
left join (
  select responsavel_id, sum(quantidade_entregue) as entregues, count(distinct bloco_id) as blocos, max(created_at) as ultima_entrega,
         count(*) filter (where separada) as separados
  from public.blocos_entregas where status <> 'cancelada' group by responsavel_id
) e on e.responsavel_id = r.id
left join (
  select responsavel_id, sum(valor_devido) as devido, sum(valor_pago) as pago, max(created_at) as ultimo_acerto
  from public.blocos_acertos where not desfeito group by responsavel_id
) a on a.responsavel_id = r.id;

-- resumo por comunidade (planejado x entregue x vendido)
create or replace view public.blocos_resumo_comunidade as
select c.id, c.ordem, c.nome, c.local, c.tipo, c.forma, c.ativa,
  c.hist_1, c.hist_2, c.hist_3, c.hist_4, c.hist_5, c.sugestao, c.planejado, c.observacao,
  greatest(c.hist_1, c.hist_2, c.hist_3, c.hist_4, c.hist_5) as melhor,
  coalesce(e.blocos, 0)            as blocos_entregues,
  coalesce(e.cartelas, 0)          as cartelas_entregues,
  coalesce(x.com_responsavel, 0)   as com_responsavel,
  coalesce(x.vendidas, 0)          as vendidas,
  coalesce(x.devolvidas, 0)        as devolvidas,
  coalesce(a.devido, 0)            as valor_devido,
  coalesce(a.pago, 0)              as valor_pago,
  coalesce(a.devido, 0) - coalesce(a.pago, 0) as saldo,
  coalesce(r.qtd, 0)               as responsaveis,
  r.nomes                          as nomes_responsaveis,
  coalesce(e.separados, 0)         as blocos_separados
from public.blocos_comunidades c
left join (select comunidade_id, count(*) qtd, string_agg(nome, ', ' order by nome) nomes
             from public.blocos_responsaveis where comunidade_id is not null and not provisorio group by comunidade_id) r on r.comunidade_id = c.id
left join (select rr.comunidade_id, count(*) filter (where not e.separada) blocos, sum(e.quantidade_entregue) filter (where not e.separada) cartelas,
                  count(*) filter (where e.separada) separados
             from public.blocos_entregas e join public.blocos_responsaveis rr on rr.id = e.responsavel_id
            where e.status <> 'cancelada' and rr.comunidade_id is not null group by rr.comunidade_id) e on e.comunidade_id = c.id
left join (select rr.comunidade_id,
                  count(*) filter (where k.status = 'com_responsavel') com_responsavel,
                  count(*) filter (where k.status = 'vendida') vendidas,
                  count(*) filter (where k.status = 'devolvida') devolvidas
             from public.blocos_cartelas k join public.blocos_entregas e on e.id = k.entrega_id
             join public.blocos_responsaveis rr on rr.id = e.responsavel_id
            where e.status <> 'cancelada' and rr.comunidade_id is not null group by rr.comunidade_id) x on x.comunidade_id = c.id
left join (select rr.comunidade_id, sum(a.valor_devido) devido, sum(a.valor_pago) pago
             from public.blocos_acertos a join public.blocos_responsaveis rr on rr.id = a.responsavel_id
            where not a.desfeito and rr.comunidade_id is not null group by rr.comunidade_id) a on a.comunidade_id = c.id;

-- resumo por bloco (catálogo, formulário de visita, blocos livres)
create or replace view public.blocos_resumo_bloco as
select b.id, b.sequencial, b.numero_inicial, b.numero_final, b.quantidade,
  count(*) filter (where c.status = 'estoque')         as estoque,
  count(*) filter (where c.status = 'com_responsavel') as com_responsavel,
  count(*) filter (where c.status = 'vendida')         as vendidas,
  count(*) filter (where c.status = 'devolvida')       as devolvidas,
  (select string_agg(distinct r.nome, ', ')
     from public.blocos_entregas e join public.blocos_responsaveis r on r.id = e.responsavel_id
    where e.bloco_id = b.id and e.status <> 'cancelada') as responsaveis
from public.blocos b join public.blocos_cartelas c on c.bloco_id = b.id
group by b.id, b.sequencial, b.numero_inicial, b.numero_final, b.quantidade;

-- ---------------------------------------------------------------------
-- 8. PAINEL (tudo calculado no banco, rápido mesmo com 30 mil cartelas)
-- ---------------------------------------------------------------------
create or replace function public.fpss_blocos_painel() returns jsonb
language sql stable as $$
  select jsonb_build_object(
    'config', (select to_jsonb(c) from public.blocos_config c where id = 1),
    'cartelas', (select jsonb_build_object(
        'total', count(*),
        'estoque', count(*) filter (where status = 'estoque'),
        'com_responsavel', count(*) filter (where status = 'com_responsavel'),
        'vendidas', count(*) filter (where status = 'vendida'),
        'devolvidas', count(*) filter (where status = 'devolvida'),
        'separadas', (select coalesce(sum(quantidade_entregue), 0) from public.blocos_entregas where separada and status = 'ativa')
      ) from public.blocos_cartelas),
    'blocos', (select jsonb_build_object(
        'total', count(*),
        'livres', count(*) filter (where livres = qtd),
        'na_rua', count(*) filter (where com_resp > 0)
      ) from (select b.id, b.quantidade as qtd,
                     count(*) filter (where c.status in ('estoque','devolvida')) as livres,
                     count(*) filter (where c.status = 'com_responsavel') as com_resp
              from public.blocos b join public.blocos_cartelas c on c.bloco_id = b.id group by b.id) x),
    'financeiro', (select jsonb_build_object(
        'bruto', coalesce(sum(valor_bruto), 0),
        'comissao', coalesce(sum(valor_comissao), 0),
        'devido', coalesce(sum(valor_devido), 0),
        'pago', coalesce(sum(valor_pago), 0),
        'saldo', coalesce(sum(valor_devido), 0) - coalesce(sum(valor_pago), 0),
        'acertos', count(*)
      ) from public.blocos_acertos where not desfeito),
    'por_plano', (select coalesce(jsonb_agg(p order by p->>'plano'), '[]'::jsonb) from (
        select jsonb_build_object(
          'plano', e.plano_nome,
          'entregues', sum(e.quantidade_entregue),
          'com_responsavel', sum(x.com_resp),
          'vendidas', sum(x.vend),
          'devolvidas', sum(x.dev),
          'devido', coalesce(sum(ai.devido), 0)
        ) as p
        from public.blocos_entregas e
        left join lateral (select count(*) filter (where status = 'com_responsavel') com_resp,
                                  count(*) filter (where status = 'vendida') vend,
                                  count(*) filter (where status = 'devolvida') dev
                           from public.blocos_cartelas where entrega_id = e.id) x on true
        left join lateral (select sum(i.valor_devido) devido from public.blocos_acerto_itens i
                           join public.blocos_acertos a on a.id = i.acerto_id
                           where i.entrega_id = e.id and not a.desfeito) ai on true
        where e.status <> 'cancelada'
        group by e.plano_nome) q),
    'por_lancador', (select coalesce(jsonb_agg(l order by l->>'lancador'), '[]'::jsonb) from (
        select jsonb_build_object(
          'lancador', nome,
          'entregas', sum(entregas), 'cartelas_entregues', sum(cartelas),
          'acertos', sum(acertos), 'recebido', sum(recebido)
        ) as l
        from (
          select coalesce(lancador_nome, '—') nome, count(*) entregas, sum(quantidade_entregue) cartelas, 0 acertos, 0::numeric recebido
            from public.blocos_entregas where status <> 'cancelada' group by 1
          union all
          select coalesce(lancador_nome, '—'), 0, 0, count(*), sum(valor_pago)
            from public.blocos_acertos where not desfeito group by 1
        ) u group by nome) q),
    'por_distribuidor', (select coalesce(jsonb_agg(d order by d->>'distribuidor'), '[]'::jsonb) from (
        select jsonb_build_object(
          'distribuidor', coalesce(e.distribuidor_nome, '(sem distribuidor)'),
          'blocos', count(*), 'cartelas', sum(e.quantidade_entregue),
          'com_responsavel', sum(x.com_resp), 'vendidas', sum(x.vend), 'devolvidas', sum(x.dev)
        ) as d
        from public.blocos_entregas e
        left join lateral (select count(*) filter (where status = 'com_responsavel') com_resp,
                                  count(*) filter (where status = 'vendida') vend,
                                  count(*) filter (where status = 'devolvida') dev
                           from public.blocos_cartelas where entrega_id = e.id) x on true
        where e.status <> 'cancelada'
        group by coalesce(e.distribuidor_nome, '(sem distribuidor)')) q),
    'pendentes', (select coalesce(jsonb_agg(to_jsonb(r) order by r.com_responsavel desc, r.saldo desc), '[]'::jsonb)
                  from (select id, nome, comunidade, telefone, com_responsavel, saldo, ultima_entrega
                        from public.blocos_resumo_responsavel
                        where com_responsavel > 0 or saldo > 0
                        order by com_responsavel desc, saldo desc limit 300) r)
  );
$$;

-- ---------------------------------------------------------------------
-- 9. PERMISSÕES: só o servidor (service_role). Público (anon) e
--    usuários logados direto no Supabase NÃO veem nem executam nada.
-- ---------------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array['blocos_config','blocos_planos','blocos','blocos_cartelas','blocos_responsaveis',
                           'blocos_recibos','blocos_entregas','blocos_acertos','blocos_acerto_itens','blocos_historico',
                           'blocos_resumo_responsavel','blocos_resumo_bloco','blocos_comunidades','blocos_resumo_comunidade','blocos_distribuidores'] loop
    execute format('revoke all on public.%I from public', t);
    if exists (select 1 from pg_roles where rolname = 'anon') then execute format('revoke all on public.%I from anon', t); end if;
    if exists (select 1 from pg_roles where rolname = 'authenticated') then execute format('revoke all on public.%I from authenticated', t); end if;
    if exists (select 1 from pg_roles where rolname = 'service_role') then execute format('grant all on public.%I to service_role', t); end if;
  end loop;
end $$;

do $$
declare f text;
begin
  for f in select p.oid::regprocedure::text from pg_proc p join pg_namespace n on n.oid = p.pronamespace
           where n.nspname = 'public' and p.proname like 'fpss\_blocos\_%' loop
    execute format('revoke all on function %s from public', f);
    if exists (select 1 from pg_roles where rolname = 'anon') then execute format('revoke all on function %s from anon', f); end if;
    if exists (select 1 from pg_roles where rolname = 'authenticated') then execute format('revoke all on function %s from authenticated', f); end if;
    if exists (select 1 from pg_roles where rolname = 'service_role') then execute format('grant execute on function %s to service_role', f); end if;
  end loop;
end $$;

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    grant usage, select on all sequences in schema public to service_role;
  end if;
end $$;

select 'Distribuição de blocos instalada' as resultado;
