-- =====================================================================
-- FPSS 2027 — Carrinho (vários itens por pedido), entrega parcial,
-- controle de estoque, termo de retirada e caixa (PDV).
-- Data: 2026-10-04
--
-- Seguro para rodar mais de uma vez (IF NOT EXISTS / OR REPLACE).
-- Rodar no SQL Editor do Supabase (projeto FPSS dzhgawgzrpgmyopptiwl).
-- =====================================================================

-- ---------------------------------------------------------------------
-- 0. BACKUP das tabelas que serão alteradas (cópia simples, no mesmo banco)
-- ---------------------------------------------------------------------
create table if not exists public.backup_20261004_pedidos  as table public.pedidos;
create table if not exists public.backup_20261004_produtos as table public.produtos;
alter table public.backup_20261004_pedidos  enable row level security;
alter table public.backup_20261004_produtos enable row level security;

-- ---------------------------------------------------------------------
-- 1. PRODUTOS — estoque físico, horário obrigatório (churrasco), alerta
--    produtos.estoque          = DISPONÍVEL PARA VENDA (baixa no pagamento)
--    produtos.estoque_fisico   = EM ESTOQUE de verdade (baixa na entrega)
-- ---------------------------------------------------------------------
alter table public.produtos add column if not exists estoque_fisico bigint;
alter table public.produtos add column if not exists exige_horario  boolean not null default false;
alter table public.produtos add column if not exists estoque_minimo integer not null default 10;

update public.produtos set exige_horario = true where codigo = 'CHU';

-- ---------------------------------------------------------------------
-- 2. PEDIDOS — novos campos
-- ---------------------------------------------------------------------
alter table public.pedidos add column if not exists origem           text not null default 'site';   -- site | caixa
alter table public.pedidos add column if not exists forma_pagamento  text;                           -- pix | dinheiro | cartao
alter table public.pedidos add column if not exists valor_recebido   numeric(10,2);
alter table public.pedidos add column if not exists troco            numeric(10,2);
alter table public.pedidos add column if not exists termo_aceito_em  timestamptz;
alter table public.pedidos add column if not exists termo_versao     text;
alter table public.pedidos add column if not exists estoque_baixado  boolean not null default false;
alter table public.pedidos add column if not exists vendedor_id      uuid;
alter table public.pedidos add column if not exists vendedor_nome    text;
alter table public.pedidos add column if not exists caixa_sessao_id  bigint;
alter table public.pedidos add column if not exists reembolsado_em   timestamptz;
alter table public.pedidos add column if not exists reembolso_motivo text;
alter table public.pedidos add column if not exists reembolso_por    text;

create index if not exists pedidos_txid_idx            on public.pedidos (txid);
create index if not exists pedidos_codigo_pedido_idx   on public.pedidos (codigo_pedido);
create index if not exists pedidos_caixa_sessao_idx    on public.pedidos (caixa_sessao_id);
create index if not exists pedidos_status_pag_idx      on public.pedidos (status_pagamento);

-- ---------------------------------------------------------------------
-- 3. ITENS DO PEDIDO
-- ---------------------------------------------------------------------
create table if not exists public.pedido_itens (
  id                  bigint generated by default as identity primary key,
  pedido_id           bigint not null references public.pedidos(id) on delete cascade,
  produto_id          bigint references public.produtos(id) on delete set null,
  produto_codigo      text not null,
  produto_nome        text not null,
  preco_unitario      numeric(10,2) not null default 0,
  quantidade          integer not null check (quantidade > 0),
  quantidade_entregue integer not null default 0,
  exige_horario       boolean not null default false,
  created_at          timestamptz not null default now(),
  constraint pedido_itens_entregue_ok check (quantidade_entregue >= 0 and quantidade_entregue <= quantidade)
);
create index if not exists pedido_itens_pedido_idx  on public.pedido_itens (pedido_id);
create index if not exists pedido_itens_produto_idx on public.pedido_itens (produto_id);
alter table public.pedido_itens enable row level security;

-- ---------------------------------------------------------------------
-- 4. HISTÓRICO DE ENTREGAS (cada entrega: item, quantidade, hora, quem)
-- ---------------------------------------------------------------------
create table if not exists public.pedido_entregas (
  id                bigint generated by default as identity primary key,
  pedido_id         bigint not null references public.pedidos(id) on delete cascade,
  pedido_item_id    bigint not null references public.pedido_itens(id) on delete cascade,
  quantidade        integer not null check (quantidade > 0),
  entregue_em       timestamptz not null default now(),
  entregue_por      uuid,
  entregue_por_nome text,
  origem            text not null default 'retirada'   -- retirada | caixa
);
create index if not exists pedido_entregas_pedido_idx on public.pedido_entregas (pedido_id);
alter table public.pedido_entregas enable row level security;

-- ---------------------------------------------------------------------
-- 5. MOVIMENTAÇÃO DE ESTOQUE (entradas, saídas, ajustes, vendas, entregas)
--    delta_disponivel / delta_fisico: quanto mudou em cada número
-- ---------------------------------------------------------------------
create table if not exists public.estoque_movimentos (
  id               bigint generated by default as identity primary key,
  produto_id       bigint not null references public.produtos(id) on delete cascade,
  tipo             text not null check (tipo in ('inicial','entrada','saida','ajuste','venda','entrega','reembolso')),
  delta_disponivel integer not null default 0,
  delta_fisico     integer not null default 0,
  disponivel_apos  bigint,
  fisico_apos      bigint,
  motivo           text,
  pedido_id        bigint,
  usuario_id       uuid,
  usuario_nome     text,
  created_at       timestamptz not null default now()
);
create index if not exists estoque_mov_produto_idx on public.estoque_movimentos (produto_id, created_at desc);
alter table public.estoque_movimentos enable row level security;

-- ---------------------------------------------------------------------
-- 6. CAIXA — sessões (abertura/fechamento por usuário) e movimentos
-- ---------------------------------------------------------------------
create table if not exists public.caixa_sessoes (
  id                    bigint generated by default as identity primary key,
  usuario_id            uuid not null,
  usuario_nome          text,
  usuario_email         text,
  status                text not null default 'aberto' check (status in ('aberto','fechado')),
  aberto_em             timestamptz not null default now(),
  fechado_em            timestamptz,
  troco_inicial         numeric(10,2) not null default 0,
  dinheiro_contado      numeric(10,2),
  dinheiro_esperado     numeric(10,2),
  diferenca             numeric(10,2),
  total_dinheiro        numeric(10,2),
  total_pix             numeric(10,2),
  total_cartao          numeric(10,2),
  observacao_fechamento text
);
create unique index if not exists caixa_uma_aberta_por_usuario on public.caixa_sessoes (usuario_id) where status = 'aberto';
alter table public.caixa_sessoes enable row level security;

create table if not exists public.caixa_movimentos (
  id         bigint generated by default as identity primary key,
  sessao_id  bigint not null references public.caixa_sessoes(id) on delete cascade,
  tipo       text not null check (tipo in ('sangria','suprimento')),
  valor      numeric(10,2) not null check (valor > 0),
  motivo     text,
  created_at timestamptz not null default now()
);
create index if not exists caixa_mov_sessao_idx on public.caixa_movimentos (sessao_id);
alter table public.caixa_movimentos enable row level security;

-- ---------------------------------------------------------------------
-- 7. MIGRAR PEDIDOS ANTIGOS (1 produto por pedido) para pedido_itens
-- ---------------------------------------------------------------------
insert into public.pedido_itens
  (pedido_id, produto_id, produto_codigo, produto_nome, preco_unitario, quantidade, quantidade_entregue, exige_horario, created_at)
select
  p.id,
  pr.id,
  coalesce(p.produto_tipo, 'CHU'),
  coalesce(pr.nome, p.produto_tipo, 'Produto'),
  coalesce(p.valor_unitario, case when coalesce(p.quantidade,0) > 0 then p.valor_total / p.quantidade else p.valor_total end, 0),
  greatest(coalesce(p.quantidade, 1), 1),
  case when p.status_retirada = 'retirado' then greatest(coalesce(p.quantidade, 1), 1) else 0 end,
  coalesce(pr.exige_horario, false),
  p.created_at
from public.pedidos p
left join public.produtos pr on pr.codigo = coalesce(p.produto_tipo, 'CHU')
where not exists (select 1 from public.pedido_itens i where i.pedido_id = p.id);

-- Pedidos antigos já pagos: considera o estoque já "baixado" (não desconta
-- de novo o que foi vendido antes deste sistema existir).
update public.pedidos set estoque_baixado = true
where status_pagamento = 'pago' and estoque_baixado = false;

-- Estoque físico inicial = disponível + o que já foi pago e ainda não entregue
update public.produtos pr
set estoque_fisico = coalesce(pr.estoque, 0) + coalesce((
  select sum(i.quantidade - i.quantidade_entregue)
  from public.pedido_itens i
  join public.pedidos p on p.id = i.pedido_id
  where i.produto_id = pr.id and p.status_pagamento = 'pago' and p.reembolsado_em is null
), 0)
where pr.estoque_fisico is null;

insert into public.estoque_movimentos (produto_id, tipo, delta_disponivel, delta_fisico, disponivel_apos, fisico_apos, motivo)
select pr.id, 'inicial', 0, 0, pr.estoque, pr.estoque_fisico, 'Saldo inicial ao ativar o controle de estoque'
from public.produtos pr
where not exists (select 1 from public.estoque_movimentos m where m.produto_id = pr.id);

-- ---------------------------------------------------------------------
-- 8. FUNÇÕES (atômicas — evitam erro quando vários caixas agem ao mesmo tempo)
-- ---------------------------------------------------------------------

-- 8.1 Cria pedido + itens numa transação só, gerando o código pelo id
create or replace function public.fpss_criar_pedido(p_pedido jsonb, p_itens jsonb, p_prefixo text)
returns jsonb
language plpgsql
as $$
declare
  v_id bigint;
  v_codigo text;
  v_item jsonb;
begin
  insert into public.pedidos (
    nome, sobrenome, cpf, telefone, email, produto_tipo, quantidade, valor_unitario,
    horario_retirada, valor_total, txid, pix_copia_cola, status_pagamento, status_retirada,
    status, origem, forma_pagamento, valor_recebido, troco, termo_aceito_em, termo_versao,
    vendedor_id, vendedor_nome, caixa_sessao_id, data_pagamento
  ) values (
    p_pedido->>'nome', coalesce(p_pedido->>'sobrenome',''), p_pedido->>'cpf', p_pedido->>'telefone',
    p_pedido->>'email', p_pedido->>'produto_tipo', (p_pedido->>'quantidade')::bigint,
    (p_pedido->>'valor_unitario')::numeric, p_pedido->>'horario_retirada',
    (p_pedido->>'valor_total')::numeric, p_pedido->>'txid', p_pedido->>'pix_copia_cola',
    coalesce(p_pedido->>'status_pagamento','pendente'), coalesce(p_pedido->>'status_retirada','pendente'),
    coalesce(p_pedido->>'status','pendente'), coalesce(p_pedido->>'origem','site'),
    p_pedido->>'forma_pagamento', (p_pedido->>'valor_recebido')::numeric, (p_pedido->>'troco')::numeric,
    (p_pedido->>'termo_aceito_em')::timestamptz, p_pedido->>'termo_versao',
    (p_pedido->>'vendedor_id')::uuid, p_pedido->>'vendedor_nome', (p_pedido->>'caixa_sessao_id')::bigint,
    (p_pedido->>'data_pagamento')::timestamp
  ) returning id into v_id;

  v_codigo := 'FPSS-2027-' || coalesce(nullif(p_prefixo,''),'P') || '-' || lpad(v_id::text, 6, '0');
  update public.pedidos set codigo_pedido = v_codigo where id = v_id;

  for v_item in select * from jsonb_array_elements(p_itens) loop
    insert into public.pedido_itens (pedido_id, produto_id, produto_codigo, produto_nome, preco_unitario, quantidade, exige_horario)
    values (
      v_id, (v_item->>'produto_id')::bigint, v_item->>'produto_codigo', v_item->>'produto_nome',
      (v_item->>'preco_unitario')::numeric, (v_item->>'quantidade')::int,
      coalesce((v_item->>'exige_horario')::boolean, false)
    );
  end loop;

  return jsonb_build_object('id', v_id, 'codigo_pedido', v_codigo);
end;
$$;

-- 8.2 Baixa o estoque DISPONÍVEL de um pedido pago (uma única vez).
--     Permite ficar negativo (regra combinada: quem pagou leva; admin vê alerta).
create or replace function public.fpss_baixar_estoque_pedido(p_pedido_id bigint)
returns boolean
language plpgsql
as $$
declare
  v_ok boolean;
  r record;
  v_disp bigint;
  v_fis bigint;
begin
  update public.pedidos set estoque_baixado = true
  where id = p_pedido_id and estoque_baixado = false and reembolsado_em is null
  returning true into v_ok;

  if v_ok is null then
    return false;
  end if;

  for r in select produto_id, sum(quantidade)::int as qtd from public.pedido_itens
           where pedido_id = p_pedido_id and produto_id is not null group by produto_id loop
    update public.produtos set estoque = coalesce(estoque,0) - r.qtd, updated_at = now()
    where id = r.produto_id returning estoque, estoque_fisico into v_disp, v_fis;
    insert into public.estoque_movimentos (produto_id, tipo, delta_disponivel, delta_fisico, disponivel_apos, fisico_apos, motivo, pedido_id)
    values (r.produto_id, 'venda', -r.qtd, 0, v_disp, v_fis, 'Pagamento confirmado', p_pedido_id);
  end loop;

  return true;
end;
$$;

-- 8.3 Registra entrega (total ou parcial) de itens de um pedido pago.
--     p_itens = [{"item_id": 1, "quantidade": 2}, ...]
create or replace function public.fpss_registrar_entrega(
  p_pedido_id bigint, p_itens jsonb, p_usuario_id uuid, p_usuario_nome text, p_origem text
)
returns jsonb
language plpgsql
as $$
declare
  v_pedido public.pedidos%rowtype;
  v_req jsonb;
  v_item public.pedido_itens%rowtype;
  v_qtd int;
  v_total_entregue int := 0;
  v_pendente int;
  v_status text;
  v_disp bigint;
  v_fis bigint;
begin
  select * into v_pedido from public.pedidos where id = p_pedido_id for update;
  if not found then
    raise exception 'Pedido não encontrado.';
  end if;
  if v_pedido.status_pagamento <> 'pago' then
    raise exception 'Pagamento ainda não confirmado. Entrega bloqueada.';
  end if;
  if v_pedido.reembolsado_em is not null then
    raise exception 'Pedido reembolsado. Entrega bloqueada.';
  end if;

  for v_req in select * from jsonb_array_elements(coalesce(p_itens, '[]'::jsonb)) loop
    v_qtd := coalesce((v_req->>'quantidade')::int, 0);
    if v_qtd <= 0 then
      continue;
    end if;

    select * into v_item from public.pedido_itens
    where id = (v_req->>'item_id')::bigint and pedido_id = p_pedido_id for update;
    if not found then
      raise exception 'Item não pertence a este pedido.';
    end if;
    if v_qtd > (v_item.quantidade - v_item.quantidade_entregue) then
      raise exception 'Quantidade maior que o pendente para %: restam %.', v_item.produto_nome, (v_item.quantidade - v_item.quantidade_entregue);
    end if;

    update public.pedido_itens set quantidade_entregue = quantidade_entregue + v_qtd where id = v_item.id;

    insert into public.pedido_entregas (pedido_id, pedido_item_id, quantidade, entregue_por, entregue_por_nome, origem)
    values (p_pedido_id, v_item.id, v_qtd, p_usuario_id, p_usuario_nome, coalesce(p_origem, 'retirada'));

    if v_item.produto_id is not null then
      update public.produtos set estoque_fisico = coalesce(estoque_fisico,0) - v_qtd, updated_at = now()
      where id = v_item.produto_id returning estoque, estoque_fisico into v_disp, v_fis;
      insert into public.estoque_movimentos (produto_id, tipo, delta_disponivel, delta_fisico, disponivel_apos, fisico_apos, motivo, pedido_id, usuario_id, usuario_nome)
      values (v_item.produto_id, 'entrega', 0, -v_qtd, v_disp, v_fis, 'Entrega ao cliente', p_pedido_id, p_usuario_id, p_usuario_nome);
    end if;

    v_total_entregue := v_total_entregue + v_qtd;
  end loop;

  if v_total_entregue = 0 then
    raise exception 'Nenhuma quantidade informada para entrega.';
  end if;

  select coalesce(sum(quantidade - quantidade_entregue), 0) into v_pendente
  from public.pedido_itens where pedido_id = p_pedido_id;

  v_status := case when v_pendente = 0 then 'retirado' else 'parcial' end;

  update public.pedidos
  set status_retirada = v_status,
      data_retirada = case when v_pendente = 0 then now() else data_retirada end,
      updated_at = now()
  where id = p_pedido_id;

  return jsonb_build_object('status_retirada', v_status, 'entregue_agora', v_total_entregue, 'pendente', v_pendente);
end;
$$;

-- 8.4 Entrada / saída / ajuste de estoque feito pelo administrador
--     entrada: +q nos dois números | saida: -q nos dois
--     ajuste : q = quantidade CONTADA fisicamente; corrige os dois pela diferença
create or replace function public.fpss_movimentar_estoque(
  p_produto_id bigint, p_tipo text, p_quantidade int, p_motivo text, p_usuario_id uuid, p_usuario_nome text
)
returns jsonb
language plpgsql
as $$
declare
  v_prod public.produtos%rowtype;
  v_delta int;
begin
  if p_tipo not in ('entrada','saida','ajuste') then
    raise exception 'Tipo de movimentação inválido.';
  end if;
  if p_quantidade is null or p_quantidade < 0 or (p_tipo <> 'ajuste' and p_quantidade = 0) then
    raise exception 'Quantidade inválida.';
  end if;

  select * into v_prod from public.produtos where id = p_produto_id for update;
  if not found then
    raise exception 'Produto não encontrado.';
  end if;

  v_delta := case p_tipo
               when 'entrada' then p_quantidade
               when 'saida'   then -p_quantidade
               else p_quantidade - coalesce(v_prod.estoque_fisico, 0)
             end;

  update public.produtos
  set estoque = coalesce(estoque,0) + v_delta,
      estoque_fisico = coalesce(estoque_fisico,0) + v_delta,
      updated_at = now()
  where id = p_produto_id
  returning * into v_prod;

  insert into public.estoque_movimentos (produto_id, tipo, delta_disponivel, delta_fisico, disponivel_apos, fisico_apos, motivo, usuario_id, usuario_nome)
  values (p_produto_id, p_tipo, v_delta, v_delta, v_prod.estoque, v_prod.estoque_fisico, p_motivo, p_usuario_id, p_usuario_nome);

  return jsonb_build_object('estoque', v_prod.estoque, 'estoque_fisico', v_prod.estoque_fisico, 'delta', v_delta);
end;
$$;

-- 8.5 Reembolso: marca o pedido e devolve ao DISPONÍVEL o que não foi entregue
create or replace function public.fpss_reembolsar_pedido(p_pedido_id bigint, p_motivo text, p_usuario_nome text)
returns jsonb
language plpgsql
as $$
declare
  v_pedido public.pedidos%rowtype;
  r record;
  v_disp bigint;
  v_fis bigint;
begin
  select * into v_pedido from public.pedidos where id = p_pedido_id for update;
  if not found then
    raise exception 'Pedido não encontrado.';
  end if;
  if v_pedido.reembolsado_em is not null then
    raise exception 'Pedido já reembolsado.';
  end if;

  if v_pedido.estoque_baixado then
    for r in select produto_id, sum(quantidade - quantidade_entregue)::int as qtd
             from public.pedido_itens where pedido_id = p_pedido_id and produto_id is not null
             group by produto_id having sum(quantidade - quantidade_entregue) > 0 loop
      update public.produtos set estoque = coalesce(estoque,0) + r.qtd, updated_at = now()
      where id = r.produto_id returning estoque, estoque_fisico into v_disp, v_fis;
      insert into public.estoque_movimentos (produto_id, tipo, delta_disponivel, delta_fisico, disponivel_apos, fisico_apos, motivo, pedido_id, usuario_nome)
      values (r.produto_id, 'reembolso', r.qtd, 0, v_disp, v_fis, coalesce(p_motivo,'Reembolso'), p_pedido_id, p_usuario_nome);
    end loop;
  end if;

  update public.pedidos
  set reembolsado_em = now(), reembolso_motivo = p_motivo, reembolso_por = p_usuario_nome,
      status = 'reembolsado', updated_at = now()
  where id = p_pedido_id;

  return jsonb_build_object('ok', true);
end;
$$;

-- Só o servidor (service_role) pode chamar essas funções — nunca o navegador.
revoke all on function public.fpss_criar_pedido(jsonb, jsonb, text)                          from public, anon, authenticated;
revoke all on function public.fpss_baixar_estoque_pedido(bigint)                             from public, anon, authenticated;
revoke all on function public.fpss_registrar_entrega(bigint, jsonb, uuid, text, text)        from public, anon, authenticated;
revoke all on function public.fpss_movimentar_estoque(bigint, text, int, text, uuid, text)   from public, anon, authenticated;
revoke all on function public.fpss_reembolsar_pedido(bigint, text, text)                     from public, anon, authenticated;
grant execute on function public.fpss_criar_pedido(jsonb, jsonb, text)                        to service_role;
grant execute on function public.fpss_baixar_estoque_pedido(bigint)                           to service_role;
grant execute on function public.fpss_registrar_entrega(bigint, jsonb, uuid, text, text)      to service_role;
grant execute on function public.fpss_movimentar_estoque(bigint, text, int, text, uuid, text) to service_role;
grant execute on function public.fpss_reembolsar_pedido(bigint, text, text)                   to service_role;

-- Conferência final
select codigo, nome, estoque as disponivel, estoque_fisico as em_estoque, exige_horario, estoque_minimo from public.produtos order by ordem;
