-- =====================================================================
-- FPSS 2027 — Novos perfis (Operador de Caixa, Equipe do Bingo),
-- acesso personalizado por usuário e origem das visitas (parcerias).
-- Data: 2026-10-06 — pode rodar mais de uma vez (seguro).
-- Rode DEPOIS do 2026-10-05b-perfis-de-acesso.sql (já rodado).
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. PERFIS: operador_caixa e equipe_bingo
-- ---------------------------------------------------------------------
alter table public.user_profiles drop constraint if exists user_profiles_role_check;
alter table public.user_profiles add constraint user_profiles_role_check
  check (role in ('admin','padrao','voluntario','operador_caixa','equipe_bingo','usuario'));

alter table public.perfis_acesso drop constraint if exists perfis_acesso_papel_check;
alter table public.perfis_acesso add constraint perfis_acesso_papel_check
  check (papel in ('padrao','voluntario','operador_caixa','equipe_bingo'));

-- telas iniciais dos perfis novos (só cria; não mexe no que você já marcou)
insert into public.perfis_acesso (papel, paginas) values
  ('operador_caixa', array['caixa','caixas','retirada','leitor']),
  ('equipe_bingo',   array['central','cartelas','blocos','leitor'])
on conflict (papel) do nothing;

-- ---------------------------------------------------------------------
-- 2. ACESSO PERSONALIZADO POR USUÁRIO
--    null  = usa as telas do perfil
--    lista = usa exatamente estas telas (o perfil não vale para ele)
-- ---------------------------------------------------------------------
alter table public.user_profiles add column if not exists paginas_personalizadas text[];

-- quem tinha "Blocos" liberado só para si (acesso_blocos) passa para o
-- acesso personalizado: telas do perfil + Blocos
update public.user_profiles u
   set paginas_personalizadas = (select array(select distinct x from unnest(coalesce(p.paginas, '{}') || array['blocos']) x)),
       acesso_blocos = false
  from public.perfis_acesso p
 where p.papel = u.role
   and u.acesso_blocos = true
   and u.role <> 'admin'
   and u.paginas_personalizadas is null;

-- ---------------------------------------------------------------------
-- 3. ORIGEM DAS VISITAS (de onde chegam: Instagram, sites parceiros…)
--    Só números por dia/origem — nenhum dado pessoal.
-- ---------------------------------------------------------------------
create table if not exists public.origem_visitas (
  dia      date not null default (now() at time zone 'America/Porto_Velho')::date,
  origem   text not null,
  meio     text not null default '',
  campanha text not null default '',
  pagina   text not null default '',
  visitas  int  not null default 0,
  primary key (dia, origem, meio, campanha, pagina)
);

-- compras (Pix gerados) com a origem de quem comprou — só o código do Pix
create table if not exists public.origem_compras (
  txid      text primary key,
  tipo      text not null check (tipo in ('produto','cartela')),
  origem    text not null,
  meio      text not null default '',
  campanha  text not null default '',
  criado_em timestamptz not null default now()
);
create index if not exists origem_compras_origem_idx on public.origem_compras (origem);

-- links curtos/rotulados criados no admin (gerador de links)
create table if not exists public.origem_links (
  id         bigint generated by default as identity primary key,
  nome       text not null,
  origem     text not null,
  meio       text not null default '',
  campanha   text not null default '',
  destino    text not null default '/',
  criado_por text,
  criado_em  timestamptz not null default now()
);

create or replace function public.fpss_origem_visita(p_origem text, p_meio text, p_campanha text, p_pagina text)
returns void language sql as $$
  insert into public.origem_visitas (dia, origem, meio, campanha, pagina, visitas)
  values ((now() at time zone 'America/Porto_Velho')::date,
          left(coalesce(nullif(p_origem, ''), 'direto'), 60), left(coalesce(p_meio, ''), 40),
          left(coalesce(p_campanha, ''), 60), left(coalesce(p_pagina, ''), 80), 1)
  on conflict (dia, origem, meio, campanha, pagina)
  do update set visitas = public.origem_visitas.visitas + 1;
$$;

-- só o servidor (service_role) lê e grava
do $$
declare t text;
begin
  foreach t in array array['origem_visitas','origem_compras','origem_links'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on public.%I from public', t);
    if exists (select 1 from pg_roles where rolname = 'anon') then execute format('revoke all on public.%I from anon', t); end if;
    if exists (select 1 from pg_roles where rolname = 'authenticated') then execute format('revoke all on public.%I from authenticated', t); end if;
    if exists (select 1 from pg_roles where rolname = 'service_role') then execute format('grant all on public.%I to service_role', t); end if;
  end loop;
  revoke all on function public.fpss_origem_visita(text, text, text, text) from public;
  if exists (select 1 from pg_roles where rolname = 'anon') then revoke all on function public.fpss_origem_visita(text, text, text, text) from anon; end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then revoke all on function public.fpss_origem_visita(text, text, text, text) from authenticated; end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then grant execute on function public.fpss_origem_visita(text, text, text, text) to service_role; end if;
end $$;
grant usage, select on all sequences in schema public to service_role;

-- conferência
select papel, paginas from public.perfis_acesso order by papel;
select role, count(*) from public.user_profiles group by role order by role;
